package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// CVFavoriteSpec describes a request to add/remove a favorite for a CV
// Example: the operator will call the provided ServiceURL to apply the change.
type CVFavoriteSpec struct {
	// ServiceURL is the base URL of the favorites service (e.g. http://favorites.svc.cluster.local:8080)
	ServiceURL string `json:"serviceURL"`
	// CVID is the database id of the CV to favorite
	CVID string `json:"cvId"`
	// UserID is the id of the user performing the favorite
	UserID string `json:"userId"`
	// Action is either "add" or "remove"
	Action string `json:"action"`
}

// CVFavoriteStatus reports the result of attempting to apply the favorite
type CVFavoriteStatus struct {
	// Synced indicates the operator successfully applied the action
	Synced bool `json:"synced,omitempty"`
	// Message contains human-readable status or error
	Message string `json:"message,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Synced",type="boolean",JSONPath=".status.synced"
// +kubebuilder:resource:path=cvfavorites,shortName=cvf
type CVFavorite struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CVFavoriteSpec   `json:"spec,omitempty"`
	Status CVFavoriteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type CVFavoriteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CVFavorite `json:"items"`
}

// DeepCopyInto copies all properties of this object into out. in must be non-nil.
func (in *CVFavorite) DeepCopyInto(out *CVFavorite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CVFavorite.
func (in *CVFavorite) DeepCopy() *CVFavorite {
	if in == nil {
		return nil
	}
	out := new(CVFavorite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object
func (in *CVFavorite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for CVFavoriteList
func (in *CVFavoriteList) DeepCopyInto(out *CVFavoriteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]CVFavorite, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy creates a new CVFavoriteList
func (in *CVFavoriteList) DeepCopy() *CVFavoriteList {
	if in == nil {
		return nil
	}
	out := new(CVFavoriteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object
func (in *CVFavoriteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
