package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// SimpleConfigSpec is the user-provided configuration to store in a ConfigMap
type SimpleConfigSpec struct {
	// Data is a map of key/value pairs to store
	Data map[string]string `json:"data,omitempty"`
}

// SimpleConfigStatus contains information about the created ConfigMap
type SimpleConfigStatus struct {
	// ConfigMapName is the name of the generated ConfigMap
	ConfigMapName string `json:"configMapName,omitempty"`
	// Synced indicates whether the operator has successfully synced the ConfigMap
	Synced bool `json:"synced,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Synced",type="boolean",JSONPath=".status.synced"
type SimpleConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SimpleConfigSpec   `json:"spec,omitempty"`
	Status SimpleConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type SimpleConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SimpleConfig `json:"items"`
}

// DeepCopyInto copies all properties of this object into out. in must be non-nil.
func (in *SimpleConfig) DeepCopyInto(out *SimpleConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec.Data != nil {
		out.Spec.Data = make(map[string]string, len(in.Spec.Data))
		for k, v := range in.Spec.Data {
			out.Spec.Data[k] = v
		}
	}
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleConfig.
func (in *SimpleConfig) DeepCopy() *SimpleConfig {
	if in == nil {
		return nil
	}
	out := new(SimpleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object
func (in *SimpleConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SimpleConfigList
func (in *SimpleConfigList) DeepCopyInto(out *SimpleConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SimpleConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy creates a new SimpleConfigList
func (in *SimpleConfigList) DeepCopy() *SimpleConfigList {
	if in == nil {
		return nil
	}
	out := new(SimpleConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object
func (in *SimpleConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
